config/routes.rb
Gurujipooja::Application.routes.draw do

  resources :states

  resources :countries

  resources :videos

	match "/booking/new_booking", :to => "booking#new_booking", :as => :new_booking
	match "/booking/create_booking", :to => "booking#create_booking", :as => :create_booking
	match "/booking/update_booking", :to => "booking#update_booking", :as => :update_booking
  match "/import_cities", :to => "cities#import_cities"

	devise_scope :user do
		get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
	end
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }	

  resources :plans

  resources :locations 

  resources :cities

  resources :pujas

  resources :contacts

	match "/enable_user", :to => "admin#approve_user", :as => :enable_user
	match "/search", :to => "site#search", :as => :search

  devise_for :users
	
	match "/get_daily_events", :to => "daily_events#get_daily_events"

  resources :daily_events
  
 	match "/services", :to => "services#numerology"
	match "/puja_vidhi", :to => "site#pooja_vidhi", :as => :pooja_vidhi
  match "/calendar", :to => "site#calendar", :as => :calendar	
  match "/about_us", :to => "site#about_us", :as => :about_us		
  match "/feedback", :to => "site#feedback", :as => :feedback	
  match "/faqs", :to => "site#faq", :as => :faq		
  match "/contact-us", :to => "site#contact_us", :as => :contact_us	
  match "/guruji/:id", :to => "site#guruji"
  match "/terms_and_conditions", :to => "site#terms", :as => :terms
  match "/gurujiforpuja_site_map", :to => "site#site_map", :as => :site_map
  match "/gurujiforpuja_privacy_policy", :to => "site#privacy_policy", :as => :privacy_policy
  match "/site/plans", :to => "site#plan"
  
  match '/assets/crop', :to => 'assets#crop'
	match '/assets/crop_image', :to => 'assets#crop_image'
	match "/assets/add_lookbook",:to => "assets#add_lookbook"
	match '/assets/variant_assets', :to => 'assets#variant_assets'
	match '/assets/add_to_variants', :to => 'assets#add_to_variants'
	match '/assets/upload_assets', :to => 'assets#upload_assets'
  match '/assets/delete_assets', :to => 'assets#delete_assets'
  match '/assets/create_video', :to => 'assets#create_video'
  match '/assets/new_video', :to => 'assets#new_video'
  match '/assets/video', :to => 'assets#video'
  match '/assets/video_status', :to => 'assets#video_status'
  match '/assets/logo', :to => 'assets#logo'
  match '/assets/add', :to => 'assets#add'
  match '/assets/:id/destroy', :to => 'assets#destroy'
  match '/assets/add_logo', :to => 'assets#add_logo'
  match '/assets/show_update_asset', :to => 'assets#show_update_asset'
  match '/assets/reorder', :to => 'assets#reorder'
  match '/assets/reorder_all', :to => 'assets#reorder_all'
	match '/assets/update', :to => 'assets#update'
	match '/assets/:id', :to => 'assets#show'
	match "/download_asset/:id", :to => "assets#download_asset", :as => :download_asset

   root :to => 'site#index'

   match ':controller(/:action(/:id))(.:format)'
   
   match "/:guruji_id", :to => "site#guruji", :as => :guruji_details
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name, :country_id

  belongs_to :country

  has_many :cities
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  # GET /states
  # GET /states.json
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/new
  # GET /states/new.json
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.json
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/states_helper.rb
module StatesHelper
	def get_states
		h = {}
		State.all.each{|c| h[c.name] = c.id}
		return h
	end

end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    <%= f.label :country_id %><br />
    <%= f.select :country_id, get_countries %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @states.each do |state| %>
  <tr>
    <td><%= state.name %></td>
    <td><%= link_to 'Show', state %></td>
    <td><%= link_to 'Edit', edit_state_path(state) %></td>
    <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @state.name %>
</p>


<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>