config/routes.rb
Gurujipooja::Application.routes.draw do

  resources :states

  resources :countries

  resources :videos

	match "/booking/new_booking", :to => "booking#new_booking", :as => :new_booking
	match "/booking/create_booking", :to => "booking#create_booking", :as => :create_booking
	match "/booking/update_booking", :to => "booking#update_booking", :as => :update_booking
  match "/import_cities", :to => "cities#import_cities"

	devise_scope :user do
		get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
	end
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }	

  resources :plans

  resources :locations 

  resources :cities

  resources :pujas

  resources :contacts

	match "/enable_user", :to => "admin#approve_user", :as => :enable_user
	match "/search", :to => "site#search", :as => :search

  devise_for :users
	
	match "/get_daily_events", :to => "daily_events#get_daily_events"

  resources :daily_events
  
 	match "/services", :to => "services#numerology"
	match "/puja_vidhi", :to => "site#pooja_vidhi", :as => :pooja_vidhi
  match "/calendar", :to => "site#calendar", :as => :calendar	
  match "/about_us", :to => "site#about_us", :as => :about_us		
  match "/feedback", :to => "site#feedback", :as => :feedback	
  match "/faqs", :to => "site#faq", :as => :faq		
  match "/contact-us", :to => "site#contact_us", :as => :contact_us	
  match "/guruji/:id", :to => "site#guruji"
  match "/terms_and_conditions", :to => "site#terms", :as => :terms
  match "/gurujiforpuja_site_map", :to => "site#site_map", :as => :site_map
  match "/gurujiforpuja_privacy_policy", :to => "site#privacy_policy", :as => :privacy_policy
  match "/site/plans", :to => "site#plan"
  
  match '/assets/crop', :to => 'assets#crop'
	match '/assets/crop_image', :to => 'assets#crop_image'
	match "/assets/add_lookbook",:to => "assets#add_lookbook"
	match '/assets/variant_assets', :to => 'assets#variant_assets'
	match '/assets/add_to_variants', :to => 'assets#add_to_variants'
	match '/assets/upload_assets', :to => 'assets#upload_assets'
  match '/assets/delete_assets', :to => 'assets#delete_assets'
  match '/assets/create_video', :to => 'assets#create_video'
  match '/assets/new_video', :to => 'assets#new_video'
  match '/assets/video', :to => 'assets#video'
  match '/assets/video_status', :to => 'assets#video_status'
  match '/assets/logo', :to => 'assets#logo'
  match '/assets/add', :to => 'assets#add'
  match '/assets/:id/destroy', :to => 'assets#destroy'
  match '/assets/add_logo', :to => 'assets#add_logo'
  match '/assets/show_update_asset', :to => 'assets#show_update_asset'
  match '/assets/reorder', :to => 'assets#reorder'
  match '/assets/reorder_all', :to => 'assets#reorder_all'
	match '/assets/update', :to => 'assets#update'
	match '/assets/:id', :to => 'assets#show'
	match "/download_asset/:id", :to => "assets#download_asset", :as => :download_asset

   root :to => 'site#index'

   match ':controller(/:action(/:id))(.:format)'
   
   match "/:guruji_id", :to => "site#guruji", :as => :guruji_details
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :name, :tags, :url, :user_id

	belongs_to :guruji, :foreign_key => :user_id
	
	validates :name, :url, :presence => true
  
  before_create :check_count
	
	private
	
	def check_count
		if self.guruji.plan and self.guruji.plan.videos_limit > self.guruji.videos.count
			return true
		else
			self.errors.add :videos, "Your maximum video upload limit is reached."
			return false
		end 
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  layout "dashboard"
  
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all 

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html { render :layout => false } # new.html.erb
      format.js
      format.json { render json: @video }
    end
    
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
     respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @video }
    end
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])
    @success = @video.save
    
    respond_to do |format|
      if @success
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.js
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.js
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.js
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.js
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    session[:deleted_video_id] = params[:id]
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.js
      format.json { head :no_content }
    end
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video, :remote => true) do |f| %> 
  <div id="video_errors">
    <% if @video.errors.any? %>
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
	  <% end %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_area :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/_snap.html.erb
<div id = "guruji_video_<%= video.id %>">
	<div class = "show_video_div">
		<a href="<%= video.url%>" rel="video_colorbox">
			<img src = "<%= asset_path('video-play.jpg') %>" width = "100px"></a>
			<p style = "font-size: 10px; text-align: center;">
			    <%= video.name %>
			</p>
			<% if current_user %>
				<% if video.guruji.id == current_user.id %>
					<%= link_to 'Destroy', video, method: :delete,:remote => true, data: { confirm: 'Are you sure?' } %> |
					<%= link_to 'Edit', edit_video_path(video) %>
				<% end %>
			<% end -%>
		
	</div>
</div>
<script>
	$("a[rel='video_colorbox']").colorbox(video_colorbox_hash);
</script>

app/views/videos/create.js.erb
<% if @success %>
	$("#div_videos").append("<%= escape_javascript(render(:partial => 'videos/snap', :locals => { :video => @video })) %>");
	$.fn.colorbox.close();
<% else %>
	$("#video_errors").html("<%= escape_javascript(render(:partial => 'layouts/errors', :locals => { :target => @video })) %>");
<% end %>

app/views/videos/destroy.js.erb
$("#guruji_video_<%= session[:deleted_video_id] %>").fadeOut();

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Description</th>
    <th>Tags</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.name %></td>
    <td><%= video.url %></td>
    <td><%= video.description %></td>
    <td><%= video.tags %></td>
    <td><%= video.user_id %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>
<%= render :partial => 'videos/form' %>

app/views/videos/new.js.erb
$("#add_video_js_div").html("<%= escape_javascript(render(:partial => 'new_partial'))%>");

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @video.name %>
</p>

<p>
  <b>Url:</b>
  <%= @video.url %>
</p>

<p>
  <b>Description:</b>
  <%= @video.description %>
</p>

<p>
  <b>Tags:</b>
  <%= @video.tags %>
</p>

<p>
  <b>User:</b>
  <%= @video.user_id %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>