config/routes.rb
Gurujipooja::Application.routes.draw do

  resources :states

  resources :countries

  resources :videos

	match "/booking/new_booking", :to => "booking#new_booking", :as => :new_booking
	match "/booking/create_booking", :to => "booking#create_booking", :as => :create_booking
	match "/booking/update_booking", :to => "booking#update_booking", :as => :update_booking
  match "/import_cities", :to => "cities#import_cities"

	devise_scope :user do
		get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
	end
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }	

  resources :plans

  resources :locations 

  resources :cities

  resources :pujas

  resources :contacts

	match "/enable_user", :to => "admin#approve_user", :as => :enable_user
	match "/search", :to => "site#search", :as => :search

  devise_for :users
	
	match "/get_daily_events", :to => "daily_events#get_daily_events"

  resources :daily_events
  
 	match "/services", :to => "services#numerology"
	match "/puja_vidhi", :to => "site#pooja_vidhi", :as => :pooja_vidhi
  match "/calendar", :to => "site#calendar", :as => :calendar	
  match "/about_us", :to => "site#about_us", :as => :about_us		
  match "/feedback", :to => "site#feedback", :as => :feedback	
  match "/faqs", :to => "site#faq", :as => :faq		
  match "/contact-us", :to => "site#contact_us", :as => :contact_us	
  match "/guruji/:id", :to => "site#guruji"
  match "/terms_and_conditions", :to => "site#terms", :as => :terms
  match "/gurujiforpuja_site_map", :to => "site#site_map", :as => :site_map
  match "/gurujiforpuja_privacy_policy", :to => "site#privacy_policy", :as => :privacy_policy
  match "/site/plans", :to => "site#plan"
  
  match '/assets/crop', :to => 'assets#crop'
	match '/assets/crop_image', :to => 'assets#crop_image'
	match "/assets/add_lookbook",:to => "assets#add_lookbook"
	match '/assets/variant_assets', :to => 'assets#variant_assets'
	match '/assets/add_to_variants', :to => 'assets#add_to_variants'
	match '/assets/upload_assets', :to => 'assets#upload_assets'
  match '/assets/delete_assets', :to => 'assets#delete_assets'
  match '/assets/create_video', :to => 'assets#create_video'
  match '/assets/new_video', :to => 'assets#new_video'
  match '/assets/video', :to => 'assets#video'
  match '/assets/video_status', :to => 'assets#video_status'
  match '/assets/logo', :to => 'assets#logo'
  match '/assets/add', :to => 'assets#add'
  match '/assets/:id/destroy', :to => 'assets#destroy'
  match '/assets/add_logo', :to => 'assets#add_logo'
  match '/assets/show_update_asset', :to => 'assets#show_update_asset'
  match '/assets/reorder', :to => 'assets#reorder'
  match '/assets/reorder_all', :to => 'assets#reorder_all'
	match '/assets/update', :to => 'assets#update'
	match '/assets/:id', :to => 'assets#show'
	match "/download_asset/:id", :to => "assets#download_asset", :as => :download_asset

   root :to => 'site#index'

   match ':controller(/:action(/:id))(.:format)'
   
   match "/:guruji_id", :to => "site#guruji", :as => :guruji_details
end

app/models/daily_event.rb
class DailyEvent < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :description, :entity_id, :entity_type, :from_time, :name, :tags, :to_time, :puja_ids
  
  validates :name, :description, :from_time, :to_time, :presence => true
  
  has_one :photo, :as => :attachable, :class_name => "Image", :dependent => :destroy, :conditions => { :group_id => "photo" }
  
  def pujas
  	Puja.where(:id => (self.puja_ids.split("|") rescue []))
  end

  def single_url(label=:mini)
  	return 	pujas.collect{|x| x.photo.url(:mini) rescue '/assets/ganpati.png'}.first
  	#return (photo.url(label) rescue "/assets/ganpati.png")
  end
  
  def puja_url(puja_id)
  	Puja.find(puja_id).photo.url(:mini) rescue '/assets/ganpati.png'
  end
  
  def url(label=:mini)
  	return 	pujas.collect{|x| x.photo.url(:mini) rescue '/assets/ganpati.png'}.join("|")
  	#return (photo.url(label) rescue "/assets/ganpati.png")
  end
  
  
  def self.generate_events(from_day,days)
  	r = (from_day)..(from_day + days.days)
  	arr = [*r]
  	arr.each do |day|
  		e = self.new
  		e.from_time = day
  		e.to_time = day + 23.hours + 59.minutes
  		e.name = day.to_s
  		e.description = day.to_s
  		e.save!
  	end
  end
end

app/controllers/daily_events_controller.rb
class DailyEventsController < ApplicationController
	load_and_authorize_resource :except => [:index, :show, :get_daily_events]
	
	layout "dashboard", :except => [:show, :get_daily_events]
  # GET /daily_events
  # GET /daily_events.json
  def index
    @daily_events = DailyEvent.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @daily_events }
    end
  end
  
  def get_daily_events
    @daily_events = DailyEvent.metasearch(params[:search]).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => { :success => true, :events => @daily_events.to_json(:methods => [:url])} }
    end
  end

  # GET /daily_events/1
  # GET /daily_events/1.json
  def show
    @daily_event = DailyEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @daily_event }
    end
  end

  # GET /daily_events/new
  # GET /daily_events/new.json
  def new
    @daily_event = DailyEvent.new
		@daily_event.from_time = Date.today
		@daily_event.to_time = Date.today + 23.hours + 59.minutes	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @daily_event }
    end
  end

  # GET /daily_events/1/edit
  def edit
    @daily_event = DailyEvent.find(params[:id])
  end

  # POST /daily_events
  # POST /daily_events.json
  def create
    @daily_event = DailyEvent.new(params[:daily_event])

    respond_to do |format|
      if @daily_event.save
        format.html { redirect_to @daily_event, :notice => 'Daily event was successfully created.' }
        format.json { render :json => @daily_event, :status => :created, :location => @daily_event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @daily_event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /daily_events/1
  # PUT /daily_events/1.json
  def update
    @daily_event = DailyEvent.find(params[:id])

    respond_to do |format|
      if @daily_event.update_attributes(params[:daily_event])
        format.html { redirect_to @daily_event, :notice => 'Daily event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @daily_event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_events/1
  # DELETE /daily_events/1.json
  def destroy
    @daily_event = DailyEvent.find(params[:id])
    @daily_event.destroy

    respond_to do |format|
      format.html { redirect_to daily_events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/daily_events_helper.rb
module DailyEventsHelper
end

app/views/daily_events/_event_snap.html.erb
<div style="width:250px;padding:5px;border:solid 1px #ddd;margin-top:5px;">
	<div class="fl" style="width:60px;">
		<%= image_tag(event.puja_url(@booking.puja_id), :style => "width:50px;") %><br/>
	</div>
	<div class="fr" style="width:190px;">
		<%= event.name %><br/>
		<%= event.from_time.to_s(:date_show) %><br/>
		<%= event.description.html_safe rescue '-' %><br/>
		<a href="javascript:void(0);" date="<%= event.from_time.to_s(:date) %>" class="suggested_muhurta_link btn btn_red">Select this date</a>
	</div>
	<div class="clr"></div>
</div>

app/views/daily_events/_form.html.erb
<%= form_for(@daily_event) do |f| %>
  <% if @daily_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daily_event.errors.count, "error") %> prohibited this daily_event from being saved:</h2>

      <ul>
      <% @daily_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "tinymce" %>
  </div>
  <div class="field">
    <%= f.label :from_time %><br />
    <%= f.text_field :from_time, :class => "datetimepicker" %>
  </div>
  <div class="field">
    <%= f.label :to_time %><br />
    <%= f.text_field :to_time, :class => "datetimepicker" %>
  </div>
  <!--
		<div class="field">
		  <%= f.label :entity_type %><br />
		  <%= f.text_field :entity_type %>
		</div>
		<div class="field">
		  <%= f.label :entity_id %><br />
		  <%= f.number_field :entity_id %>
		</div>
		<div class="field">
		  <%= f.label :tags %><br />
		  <%= f.text_area :tags %>
		</div>
  -->

  <div><%= f.label :puja_ids %><br /><br />
	<%= f.hidden_field :puja_ids, :id => "guruji_pujas" %></div>
	
	<% get_pujas.each do |name,id| %>
		<% checked = (f.object.puja_ids.split("|") rescue []).include?(id.to_s) ? "checked='checked'" : "" %>
		<input <%= checked %> type="checkbox"  class="puja_checkbox" value="<%= id %>" id="puja_<%= id %>" name="<%= name %>"/> <label for="puja_<%= id %>"><%= name %></label><br/>
	<% end %>
	<br /><br />
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
	$("#daily_event_from_time").datetimepicker({
		ampm: true,
		dateFormat: 'yy/mm/dd'
	});
	
	$("#daily_event_to_time").datetimepicker({
		ampm: true,
		dateFormat: 'yy/mm/dd'
	});

	$(".puja_checkbox").change(function(){
		var checked = $(this).attr("checked");
		var locations = $("#guruji_pujas").val();
		var arr = new Array();
		if(locations != null && locations != ""){
			arr = locations.split("|");
		}else{
		}
		if(checked == "checked"){
			arr.push($(this).val());
		}else{
			removeByElement(arr,$(this).val());
		}
		$("#guruji_pujas").val(joinArray(arr,"|"));
	});
</script>

app/views/daily_events/edit.html.erb
<h1>Editing Muhurta</h1>

<%= render 'form' %>

<%= render :partial => "assets/singular_assets", :locals => { :entity => @daily_event, :types => ["photo"] } %>
	
<%= link_to 'Show', @daily_event %> |
<%= link_to 'Back', daily_events_path %>

app/views/daily_events/index.html.erb
<h1>Listing daily_events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>From time</th>
    <th>To time</th>
    <th>Entity type</th>
    <th>Entity</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @daily_events.each do |daily_event| %>
  <tr>
    <td><%= daily_event.name %></td>
    <td><%= daily_event.description %></td>
    <td><%= daily_event.from_time %></td>
    <td><%= daily_event.to_time %></td>
    <td><%= daily_event.entity_type %></td>
    <td><%= daily_event.entity_id %></td>
    <td><%= daily_event.tags %></td>
    <td><%= link_to 'Show', daily_event %></td>
    <td><%= link_to 'Edit', edit_daily_event_path(daily_event) %></td>
    <td><%= link_to 'Destroy', daily_event, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= paginate(@daily_events) %>
<%= link_to 'New Daily event', new_daily_event_path %>

app/views/daily_events/new.html.erb
<h1>New Muhurta</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_events_path %>

app/views/daily_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @daily_event.name %>
</p>

<p>
  <b>Description:</b>
  <%= @daily_event.description %>
</p>

<p>
  <b>From time:</b>
  <%= @daily_event.from_time %>
</p>

<p>
  <b>To time:</b>
  <%= @daily_event.to_time %>
</p>

<p>
  <b>Entity type:</b>
  <%= @daily_event.entity_type %>
</p>

<p>
  <b>Entity:</b>
  <%= @daily_event.entity_id %>
</p>

<p>
  <b>Tags:</b>
  <%= @daily_event.tags %>
</p>


<%= link_to 'Edit', edit_daily_event_path(@daily_event) %> |
<%= link_to 'Back', daily_events_path %>