config/routes.rb
Gurujipooja::Application.routes.draw do

  resources :states

  resources :countries

  resources :videos

	match "/booking/new_booking", :to => "booking#new_booking", :as => :new_booking
	match "/booking/create_booking", :to => "booking#create_booking", :as => :create_booking
	match "/booking/update_booking", :to => "booking#update_booking", :as => :update_booking
  match "/import_cities", :to => "cities#import_cities"

	devise_scope :user do
		get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
	end
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }	

  resources :plans

  resources :locations 

  resources :cities

  resources :pujas

  resources :contacts

	match "/enable_user", :to => "admin#approve_user", :as => :enable_user
	match "/search", :to => "site#search", :as => :search

  devise_for :users
	
	match "/get_daily_events", :to => "daily_events#get_daily_events"

  resources :daily_events
  
 	match "/services", :to => "services#numerology"
	match "/puja_vidhi", :to => "site#pooja_vidhi", :as => :pooja_vidhi
  match "/calendar", :to => "site#calendar", :as => :calendar	
  match "/about_us", :to => "site#about_us", :as => :about_us		
  match "/feedback", :to => "site#feedback", :as => :feedback	
  match "/faqs", :to => "site#faq", :as => :faq		
  match "/contact-us", :to => "site#contact_us", :as => :contact_us	
  match "/guruji/:id", :to => "site#guruji"
  match "/terms_and_conditions", :to => "site#terms", :as => :terms
  match "/gurujiforpuja_site_map", :to => "site#site_map", :as => :site_map
  match "/gurujiforpuja_privacy_policy", :to => "site#privacy_policy", :as => :privacy_policy
  match "/site/plans", :to => "site#plan"
  
  match '/assets/crop', :to => 'assets#crop'
	match '/assets/crop_image', :to => 'assets#crop_image'
	match "/assets/add_lookbook",:to => "assets#add_lookbook"
	match '/assets/variant_assets', :to => 'assets#variant_assets'
	match '/assets/add_to_variants', :to => 'assets#add_to_variants'
	match '/assets/upload_assets', :to => 'assets#upload_assets'
  match '/assets/delete_assets', :to => 'assets#delete_assets'
  match '/assets/create_video', :to => 'assets#create_video'
  match '/assets/new_video', :to => 'assets#new_video'
  match '/assets/video', :to => 'assets#video'
  match '/assets/video_status', :to => 'assets#video_status'
  match '/assets/logo', :to => 'assets#logo'
  match '/assets/add', :to => 'assets#add'
  match '/assets/:id/destroy', :to => 'assets#destroy'
  match '/assets/add_logo', :to => 'assets#add_logo'
  match '/assets/show_update_asset', :to => 'assets#show_update_asset'
  match '/assets/reorder', :to => 'assets#reorder'
  match '/assets/reorder_all', :to => 'assets#reorder_all'
	match '/assets/update', :to => 'assets#update'
	match '/assets/:id', :to => 'assets#show'
	match "/download_asset/:id", :to => "assets#download_asset", :as => :download_asset

   root :to => 'site#index'

   match ':controller(/:action(/:id))(.:format)'
   
   match "/:guruji_id", :to => "site#guruji", :as => :guruji_details
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :description, :duration, :name, :price, :active
  
  validates :name, :price, :active, :duration, :presence => true
  
  scope :active, where(:active => true)
  
  attr_accessor :options_hash

  @@option_variables = {
  									 "pujas_limit" => "integer",
  									 "photos_limit" => "integer",
  									 "videos_limit" => "integer",
  									 "cities_limit" => "integer",
  									 "locations_limit" => "integer",
  									 "services_limit" => "integer",
  								 }

  @@option_variables.each do |method,type|
  	attr_accessible method.to_sym
    send :define_method, "#{method.to_sym}" do
	    self.options_hash = {}
	    if self.options.present?
	      self.options_hash = ActiveSupport::JSON.decode(self.options)
      end 
      case type
    		when "boolean"
	      	return (((self.options_hash[method].to_i == 0) ? false : true) rescue false )
      	when "integer"
	      	return self.options_hash[method].to_i
	      else
	      	return self.options_hash[method]
      end
    end

    self.send(:define_method, "#{method.to_s}=") do |val|
    	self.options_hash = {}
      self.options_hash = ActiveSupport::JSON.decode(self.options) if self.options.present?
      self.options_hash[method] = val
      self.options = self.options_hash.to_json
      return val
    end
  end

  def reset_options_hash
		self.save
		return true
	end
  
  def self.option_variables
    @@option_variables
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :authenticate_user!
	load_and_authorize_resource
	layout "dashboard"
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
	def get_plans
		h = {}
		Plan.active.each{|p| h[p.name] = p.id }
		return h
	end
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "tinymce" %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active  %>
  </div>
  <% Plan.option_variables.each do |option,type| %>
  	<div class="field">
			<%= eval("f.label option.to_sym") %>
  		<% case type %>
  			<% when "integer" %>
  				<%= eval("f.text_field option.to_sym") %>
  			<% when "boolean" %>
  				<%= eval("f.check_box option.to_sym") %>
  			<% else %>
  				<%= eval("f.text_field option.to_sym") %>
  		<% end %>	
  	</div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Listing plans</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Duration</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plans.each do |plan| %>
  <tr>
    <td><%= plan.name %></td>
    <td><%= plan.price %></td>
    <td><%= plan.duration %></td>
    <td><%= plan.active ? "Yes" : "No" %></td>
    <td><%= link_to 'Show', plan %></td>
    <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
    <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @plan.name %>
</p>

<p>
  <b>Price:</b>
  <%= @plan.price %>
</p>

<p>
  <b>Duration:</b>
  <%= @plan.duration %>
</p>

<p>
  <b>Description:</b>
  <%= @plan.description.html_safe rescue "" %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>